### ISSUE TITLE
Unused warning is not deleted

### ISSUE THREAD

**Issue by sonatard** [xxpxxxxp/intellij-plugin-golangci-lint#26]
I delete following line comment, change to use `user.Name()` method.

https://github.com/sonatard/sample-project/blob/c9a50314de0866927a6241031edc2d40c494d393/main.go#L14

[.golangci.yml](https://github.com/sonatard/sample-project/blob/c9a50314de0866927a6241031edc2d40c494d393/.golangci.yml)

And I wait 20min. Unused warning is not deleted.

<img width="579" alt="スクリーンショット 2020-06-11 13 09 54" src="https://user-images.githubusercontent.com/1586910/84344629-406e0000-abe6-11ea-8d81-7d3ed45d116c.png">

I don't know whether golangci-lint is not running or it is running but failes to analysis.

```
GoLand 2020.1.3
Build #GO-201.7846.93, built on June 4, 2020
Subscription is active until October 16, 2020
Runtime version: 1.8.0_202-release-1483-b58 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 3964M
Cores: 12
```

<img width="322" alt="スクリーンショット 2020-06-11 13 32 47" src="https://user-images.githubusercontent.com/1586910/84345332-0f8eca80-abe8-11ea-8d11-cc670e693a62.png">

**Comment by xxpxxxxp** [comment]
Got it, this is because the plugin is performing analysis per folder, as running analysis for the whole project is expensive. 

The plugin just analysis the folder where you opened a file, and hold the result for reuse until some file changed in the folder.

The fail in your case is because you are changing a file outside the 'user' folder, the plugin thinks nothing changed in 'user' folder, so it will not rerun analysis but use previous results instead.

I'll add a force refresh every 1~5min even if nothing changed. Please be aware that due to performance concerns I cannot make the interval very small. Thanks for reporting the issue.

**Comment by sonatard** [comment]
Thanks. I'm looking forward to  force refresh!!

**Comment by sonatard** [comment]
And I'd like to force push manually by keyboard shortcut.

**Comment by xxpxxxxp** [comment]
Sure, I'll make it work on 'Analyze' - 'Inspect Code...'

**Comment by xxpxxxxp** [comment]
@sonatard I tested your sample project, seems golangci-lint is reporting those issues itself if `check-exported: true`

Seems `unused` has a lot false-positives
```
  unused:
    # treat code as a program (not a library) and report unused exported identifiers; default is false.
    # XXX: if you enable this setting, unused will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find funcs usages. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: false
```

Global analysis won't help, I'm sorry for misleading.

**Comment by xxpxxxxp** [comment]
@sonatard till now the `unused` linter is still miss reporting the issue even run for whole program.
I'm closing this ticket but feel free to reopen it if necessary.
