### ISSUE TITLE
Custom options not working

### ISSUE THREAD

**Issue by bojan-embroker** [xxpxxxxp/intellij-plugin-golangci-lint#43]
I have set "Custom Options" to `--config /home/<some_path>/.golangci.yml`, but I am still getting linter results based on enabled linters in the "Go Linter" settings dialog. Goland is not showing any errors related to running golangci-lint.

I don't know if it could be relevant, but Goland log has many of these entries:
` WARN - tions.ex.ConfigurableCardPanel - auto-dispose 'Go Linter' id=preference.GoLinterConfigurable `

Running `golangci-lint run --config /home/<some_path>/.golangci.yml` gives expected results.

**Comment by xxpxxxxp** [comment]
Hi @bojan-embroker , due to implementation, setting `--config` in `Custom Options` will not work properly. Actually, the config is been used but enabled linters are force replaced by the plugin.
Please considering place the `.golangci.yml` at your project root directory. That way the plugin will auto pick up your config file.

**Comment by bojan-embroker** [comment]
Hi  @xxpxxxxp,

Thank you, that works!

I also had success with putting .golangci.yml config file in my home folder. Of note is that once there is a config file that Go Linter plugin recognizes, options from its UI are ignored and per folder config files can be used too.

**Comment by xxpxxxxp** [comment]
Yeah, you've found the hidden feature ^_^

But I have to inform you, under a continuous effort to improving performance, config file will be passed directly to `golangci-lint` soon, see change: https://github.com/xxpxxxxp/intellij-plugin-golangci-lint/commit/a93467a6bf62fa26fd04477af8596c8c65f44f40

I will add support to `--config` option too, but I'm afraid you'll have to remove the "fake" `.golangci.yml` then, to make the real config file work.

**Comment by bojan-embroker** [comment]
Can you elaborate a bit what "config file will be passed directly" means? It's hard for me to understand the behaviour change by looking at the commit. Will per-folder config files still work like they do when running golangci-lint from command line?

**Comment by xxpxxxxp** [comment]
Sure, following is going to happen in the next release:
1. custom option will be entirely gone
In a survey internally, most users have no idea what the custom option is and nobody is using it. Since it can be safely replaced by config file, so it will be removed soon
2.  only project level config file will be supported
If the project is at `/user/yp/goland/project`, then config file located in `/user/yp/goland/project` `/user/yp/goland` `/user/yp` `/user` will be searched and pass to `golangci-lint` directly. Maybe `~` too, but not per-folder config files.
Since now I've found nobody using per-folder config files, and that actually conflict with #41 . Most user uses `golangci-lint` for CI, they have a single config file at project root. To align with CI result, project level config file will be supported only.

**Comment by bojan-embroker** [comment]
Could both #41 and per-folder config files be supported if golangci-lint is called without passing it a config? If most users use the same config as they do in CI, they do not need the ability to set config through setting in Goland.

**Comment by xxpxxxxp** [comment]
Plugin will pick up config file, users are not required to set it through settings.
The problem described in #41 could only be fixed by setting `golangci-lint` working dir at project root, otherwise the exclude path is incorrect, as it's a relative path from working dir. In such case, `golangci-lint` is not able to pick up per-folder config file, as its working dir is project root.

**Comment by bojan-embroker** [comment]
If I understand correctly, that change will break Go Linter plugin for us. We have other things than Go in our project and Go code isn't in the root for the project. Could you add an option to set working directory?

**Comment by xxpxxxxp** [comment]
Got you, are you probably using Intellij with a mixed project of Java & Go? By saying per-folder config files, you don't actually have different config files for each sub-folders, just one single config file under the Go project, but not the root project?
If my understanding is correct, having an option to set Go project dir would solve that case.

**Comment by bojan-embroker** [comment]
Exactly, our project is a mix of languages and all of the Go code is a single subfolder of the project root. Addition of that option would mean we could continue using Go Linter in next release of the plugin.

**Comment by xxpxxxxp** [comment]
OK, the option will be included in next release, thanks for the information.

**Comment by bojan-embroker** [comment]
That is great, thank you very much!
