### ISSUE TITLE
Avoid alert for already existing golangci-lint executable

### ISSUE THREAD

**Issue by frederikhors** [xxpxxxxp/intellij-plugin-golangci-lint#57]
I already have golangci-lint.exe in my Go bin dir.

Every time I open a new Golang project in Goland it asks me this:

`golangci-lint is custom built: v1.36.0: Download v1.36.0 in browser`

It's already 1.36.0 in my Go bin dir.

Can we fix this?

It would be amazing to get an alert only if new version is available.

Thanks again!

**Comment by xxpxxxxp** [comment]
Hi @frederikhors , would you execute `golangci-lint version --format json`
Normally the output should like `{"version":"1.36.0","commit":"6c25d06","date":"2021-01-26T13:14:05Z"}`

While seems your version is `v1.36.0` instead of `1.36.0`. The plugin is trying to tell you that the `golangci-lint` isn't an official built. From their doc `https://golangci-lint.run/usage/install/#local-installation`, custom built is not recommended unless for linter development purpose. So the plugin is suggesting you to replace it with an official binary.

**Comment by frederikhors** [comment]
Ok. Can we download it in Go bin dir instead of "`C:\Users\Public`"?

**Comment by xxpxxxxp** [comment]
Working on it, will popup folder selection before downloading.

**Comment by frederikhors** [comment]
> Working on it, will popup folder selection before downloading.

Is this released?

**Comment by xxpxxxxp** [comment]
Code ready, will be in next release.
