### ISSUE TITLE
question: can this plugin be sped up?

### ISSUE THREAD

**Issue by cyberhck** [xxpxxxxp/intellij-plugin-golangci-lint#76]
currently if I use a file watcher to use linting, it does extremely quick because it lints the current open file, with this plugin however the results are extremely slow, probably because it scans the whole thing (and doesn't seem to use cache maybe?)

and sometimes it doesn't even show the issues.

Any configuration we can do to optimize this plugin?

**Comment by xxpxxxxp** [comment]
Hi @cyberhck , some answers to your questions:
* The plugin is scanning at folder level. For a given file it lints the file's parent folder.
* It does have cache. Until change is made in the folder, open any other file in the same folder will see lints very fast.
* In case of suspecting the plugin not working, please open IDE log (`Help` - `Show Log in Finder`) and see if any error happens.
* Caused by the IDE's schedule, it's not certain when the plugin runs after you opened a file. A similar approach to the file watcher is manually trigger it by `Analyze` - `Inspect Code` (To make it easy, assign a keyboard shortcut to it) and select scope to the file. In such way the plugin is triggered immediately.

**Comment by cyberhck** [comment]
thanks for the info :slightly_smiling_face:
