### ISSUE TITLE
Roland is unable to find import references if go is installed via brew

### ISSUE THREAD

**Issue by JCzz** [xxpxxxxp/intellij-plugin-golangci-lint#94]
Goland: 2021.3
go version go1.17.3 darwin/arm64

If I install go via `brew install golang` Golang is unable to find references - I did select go version in `Preferences / Go / GOROOT`.

I worked if I installed Go using .dmg files from [go.dev](https://go.dev)

**Comment by xxpxxxxp** [comment]
Hi @JCzz , the problem is plugin says cannot find `GOROOT` when selecting the one installed with brew? But it works with the one installed by dmg? Sometimes this happens when the `GOROOT` is updated (eg. brew upgrade), please try to reopen Goland instance (Quit and Open) then redo the selection, it would be working then.

**Comment by JCzz** [comment]
Thanks @xxpxxxxp
